"""create users table

Revision ID: 199b7b0dcceb
Revises: 
Create Date: 2026-04-06 17:55:13.359968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199b7b0dcceb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('uuid', sa.UUID(as_uuid=36), nullable=True),
    sa.Column('lastseen', sa.Interval(), nullable=True),
    sa.Column('playtime', sa.Interval(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
