"""create tables

Revision ID: 1cfd4f4866bf
Revises: 35f27ed78f7c
Create Date: 2026-05-14 22:49:22.424222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cfd4f4866bf'
down_revision = '35f27ed78f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('USER', 'ADMIN', 'MOD', name='userrole'), nullable=False))
        batch_op.alter_column('uuid',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=36),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(as_uuid=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.drop_column('role')

    # ### end Alembic commands ###
