"""create tables

Revision ID: 35f27ed78f7c
Revises: d7869cdf4f03
Create Date: 2026-05-14 22:37:11.461802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f27ed78f7c'
down_revision = 'd7869cdf4f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.drop_column('world_file')
        batch_op.drop_column('modpack_file')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=36),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(as_uuid=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('archives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modpack_file', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('world_file', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('version')

    op.drop_table('archive_files')
    # ### end Alembic commands ###
