"""create tables

Revision ID: 379f584cd704
Revises: acea9d02e5d4
Create Date: 2026-05-14 22:25:31.725388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379f584cd704'
down_revision = 'acea9d02e5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=36),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(as_uuid=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    # ### end Alembic commands ###
