"""create tables

Revision ID: acea9d02e5d4
Revises: 199b7b0dcceb
Create Date: 2026-05-01 10:21:17.804662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acea9d02e5d4'
down_revision = '199b7b0dcceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('period_start', sa.Interval(), nullable=True),
    sa.Column('period_end', sa.Interval(), nullable=True),
    sa.Column('modpack_file', sa.String(length=255), nullable=True),
    sa.Column('world_file', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archives_name'), ['name'], unique=True)

    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_ip'), ['ip'], unique=True)
        batch_op.create_index(batch_op.f('ix_servers_name'), ['name'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('uuid',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=36),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(as_uuid=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_name'))
        batch_op.drop_index(batch_op.f('ix_servers_ip'))

    op.drop_table('servers')
    with op.batch_alter_table('archives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archives_name'))

    op.drop_table('archives')
    # ### end Alembic commands ###
