"""create tables

Revision ID: d7869cdf4f03
Revises: 379f584cd704
Create Date: 2026-05-14 22:27:50.135572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7869cdf4f03'
down_revision = '379f584cd704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modloader', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=36),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(as_uuid=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('archives', schema=None) as batch_op:
        batch_op.drop_column('modloader')

    # ### end Alembic commands ###
